version: '3'
services:

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

  mysql_setup:
    build: ./mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      DATABASE_SSL: 'false'
    volumes:
      - ./strapi/data:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  resources:
    build: ./resources
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: 8081
      STRAPI_HOST: strapi:1337
      STRAPI_AUTH_JWT_EXPIRATION_MS: 10000